### ISSUE TITLE
Feature 1: User can view a random work of art

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/WriteOn#1]
## ⚙️  Motivation

Writers will be able to see a random work of art that can inspire them in writing a short story

## 📐  Plan

Create a landing page that allows the user to click a button that takes them to a work of art.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-03-01 at 11 31 47 AM](https://user-images.githubusercontent.com/96929704/156235900-944424cb-ce14-47f8-bc12-9c205aa5f845.png)

## ✅ Task List

- [x] create the HTML skeleton for the landing page: 1 header, 1 main, 3 rows in the main
- [x] for the data-view attribute of the div the value = "landing-page"
- [x] Create title in the header
- [x] create the "new" link that will bring a user to the story creation page
- [x] Create the main image
- [x] create the "try it" button, which will have the same functionality as the "new" link
- [x] Create the slogan paragraph
- [x] Style the landing page appropriately so that it is compatible in mobile and desktop
- [x] create an data-view attribute with value entry-form for the second page div
- [x] Add a form that allows you to create a story entry
- [x] make all of the inputs in the form required
- [x] Make sure the form matches the style portrayed in the figma examples
- [x] Create an addEventListener to the NEW link that will render a new image on the entry page
- [x] Make sure that if a user clicks on the try it button or new link it takes them to the entry page 
- [x] Make sure clicking the try it button produces a new random image
- [x] Remove any excess styling that isn't performing a task
- [x] fix all errors
