### ISSUE TITLE
Feature 2: User can create a story and title

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/WriteOn#3]
## ⚙️ Motivation

Writers will be able to create a story and title

## 📐 Functionality

Create a responsive form that allows users to store the artwork, story and title

## 🖼️ Wireframes

<img width="749" alt="Screen Shot 2022-03-02 at 11 15 55 AM" src="https://user-images.githubusercontent.com/96929704/156432521-67b69947-0dc4-42c8-82ea-d2aff9b9def6.png">

## ✅ Task List

- [x] create a data model to store data 
- [x] Listen for submit events on the save button
      - [ ] Put the form's input values into a new object
      - [ ] Add the 'nextStoryId' to the object
      - [ ] Increment the nextStoryId on the data model
      - [ ] Prepend the new object to the entries in the data model
      - [ ] Reset the form inputs
- [x] Verify that new entries are saved to local storage along with the rest of the data model and page reload.
- [x] Verify that each new entry receives an incrementing 'entryId'
