### ISSUE TITLE
Feature: User can view previously saved stories

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/WriteOn#4]
## ⚙️  Motivation

Once a user creates a story, they'll want to see any previous stories created

## 📐 Functionality

User can see the library of stories in reverse chronological order so the newest stories are at the top of the library

## 🖼️ Wireframes

<img width="504" alt="Screen Shot 2022-03-02 at 5 07 58 PM" src="https://user-images.githubusercontent.com/96929704/156476573-336ca9fb-bb08-4f79-b3c3-a3fadba0bd8d.png">

## ✅ Task List

- [x] Add a sibling div[data-view="story-library"] to the html
- [x] Add an empty unordered list to the div above in the html
- [x] add some dummy story entries to the unordered list in the html and style them to match the wireframe
- [x] check that the library list looks good on both mobile and desktop
- [x] define a function that takes a single story entry object and returns a DOM tree that matches one of the example entries in the html
- [x] use a loop to create a DOM tree for each story entry in the data model and append it to the page when the 'DOMContentLoaded' event is fired
- [x] Remove the example html entries once the user's entries are successfully being appended to the DOM on the page load
- [x] Ensure that submitting a new story entry also creates a new DOM tree for it and adds it to the page
- [x] Ensure that submitting a new story entry automatically shows the "story-library" view without reloading the page
- [x] Ensure that refreshing the page shows the same view as before refreshing
- [x] clean up all unnecessary styling
- [x] fix all errors
