### ISSUE TITLE
Feature: User can edit a saved story

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/WriteOn#5]
## ⚙️ Motivation

User may want to go to a previous story and edit the title or the story.

## 📐 Functionality

Allow user to select a saved story and edit the story before saving the updated version.

## 🖼️ Wireframes

<img width="766" alt="Screen Shot 2022-03-03 at 1 30 50 PM" src="https://user-images.githubusercontent.com/96929704/156655976-b352c528-66f9-4569-a7d1-f66722aa2cfc.png">

## ✅ Task List

- [x] update entry rendering function to include an edit icon for each rendered entry.
- [x] Ensure that each rendered entry is given a data-entry-id attribute indicating which entry it is
- [x] Listen for clicks on the parent elements of all rendered entries
- [x] show the entry form if an edit icon was clicked 
- [x] find the matching entry object in the data model and assign it to the data model's editing property if an edit icon was clicked
- [x] Pre-populate the entry form with the clicked entry's values from the object found in the data model
- [x] update the entry form's submit handler function to conditionally add a new entry object or update the existing one.
- [x] update the entry form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] Remove all unnecessary styling
- [x] fix all errors
