### ISSUE TITLE
Feature: User can delete a saved story

### ISSUE THREAD

**Issue by SteveBehm** [SteveBehm/WriteOn#6]
## ⚙️ Motivation

Users may not like a story or want to delete an old story from their library

## 📐 Functionality

Allow users to delete an entry while editing a story

## 🖼️ Wireframes

<img width="714" alt="Screen Shot 2022-03-03 at 5 51 08 PM" src="https://user-images.githubusercontent.com/96929704/156683879-a85f6771-1b2b-4607-bf26-89dfc0690a94.png">

## ✅ Task List

- [x] Add a click target for deleting an entry to the entry form that only appears when editing a story
- [x] Show confirmation modal when user click the delete entry link
- [x] Hide the modal if the user clicks cancel
- [x] Remove the story from the data model and the entry's DOM tree from the page if the user clicks confirm.
- [x] Show the story library if the user confirms delete
- [x] Remove all excess styling
- [x] Fix all errors.
